# Estadistica Aplicada
Sesion 2. 9 agosto

Jesus Adrian Cordero Hernandez 1952778

Lista en python es una coleccion de objetos que pueden ser de distinto tipo

nombrelista = [objeto1, objeto2, objeto3, etc.]

In [1]:
alumno1 = ['Juan', 'Perez', 19]

In [2]:
type(alumno1)

list

In [3]:
alumno1

['Juan', 'Perez', 19]

In [4]:
#crear una lista con los alumnos del grupo
estadistica_g4 = ['Juan', 'Raul', 'Jimena', 'Alejandra']

In [5]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [6]:
estadistica_g4[3]

'Alejandra'

In [7]:
estadistica_g4[0]

'Juan'

In [13]:
estadistica_g4[0], estadistica_g4[3]

('Juan', 'Alejandra')

In [17]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Jimena']

In [20]:
estadistica_g4[-1]

'Alejandra'

In [21]:
estadistica_g4.remove('Jimena')

In [22]:
estadistica_g4

['Juan', 'Raul', 'Alejandra']

In [23]:
estadistica_g4.append('Alex')

In [24]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Alex']

In [25]:
amigos_bff = ['Cuqui', 'Alexa', 'Queso', 'Amaro']

In [26]:
yo = amigos_bff[3]

In [27]:
yo

'Amaro'

In [28]:
yo_enFCFM = ['Alex', 'LA', 7, 85]

In [29]:
mi_promedio = yo_enFCFM[3]
mi_carrera = yo_enFCFM[1]

In [30]:
mi_promedio, mi_carrera

(85, 'LA')

1. Instalar la libreria (una sola vez)
2. Decirle a python que use la libreria

instalar una libreria llamada yahoofinance

In [31]:
pip install yfinance

                                              0.0/63.2 kB ? eta -:--:--
     -------------------                      30.7/63.2 kB ? eta -:--:--
     --------------------------------------   61.4/63.2 kB 1.1 MB/s eta 0:00:01
     -------------------------------------- 63.2/63.2 kB 569.2 kB/s eta 0:00:00
                                              0.0/10.6 MB ? eta -:--:--
                                              0.1/10.6 MB 3.3 MB/s eta 0:00:04
     -                                        0.3/10.6 MB 3.4 MB/s eta 0:00:04
     -                                        0.5/10.6 MB 3.3 MB/s eta 0:00:04
     --                                       0.7/10.6 MB 3.6 MB/s eta 0:00:03
     ---                                      0.9/10.6 MB 3.7 MB/s eta 0:00:03
     ----                                     1.1/10.6 MB 3.8 MB/s eta 0:00:03
     ----                                     1.3/10.6 MB 4.2 MB/s eta 0:00:03
     -----                                    1.6/10.6 MB 4.4 MB/s eta

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import yfinance

In [33]:
yfinance.download('WALMEX.MX')

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2003-01-01   5.724499   5.946570   5.724499   5.879949   4.356911         0
2003-01-02   5.724499   5.946570   5.724499   5.879949   4.356911   8334330
2003-01-03   5.872546   5.909558   5.850339   5.872546   4.351425  18475096
2003-01-06   5.872546   6.116825   5.872546   6.104487   4.523288  16180223
2003-01-07   6.104487   6.104487   5.951505   5.963842   4.419074  15261074
...               ...        ...        ...        ...        ...       ...
2023-08-03  69.309998  69.349998  67.349998  67.410004  67.410004  25053073
2023-08-04  67.400002  69.099998  67.370003  69.070000  69.070000  11936860
2023-08-07  68.900002  69.589996  68.099998  68.300003  68.300003  15582252
2023-08-08  68.309998  68.639999  67.400002  67.809998  67.809998  18350539
2023-08-09  67.879997  68.750000  67.879997  68.260002  68.260002   8167945

[5213 rows x 6 columns]

# Estadistica Aplicada
### Sesion 3- 10m agosto
### Alex Amaro Rojas 1959834

Numpy (Numerical python) ayuda a manejar numeros en python (vectores, matrices, decimales)

La estructura basica de Numpy son los arreglos (arrays).Un arreglo es una coleccion de objetos del mismo tipo

Vamos a suponer que tenemos las ventas de botellas de agua de la cafeteria de la facu

Lunes 23, Martes 45, Miercoles 34, Jueves 28, Viernes 20 

In [3]:
import numpy as np

In [4]:
ventas = [23, 45, 34, 28, 20]

In [5]:
type(ventas)

list

In [7]:
ventas = np.array(ventas)

In [8]:
type(ventas)

numpy.ndarray

In [9]:
# suma 
np.sum(ventas)

150

In [10]:
# multiplicacion
np.prod(ventas)

19706400

In [11]:
# media/promedio
np.mean(ventas)

30.0

In [14]:
# valor
np.max(ventas)

45

In [13]:
# valor minimo
np.min(ventas)

20

In [15]:
# ordenar
np.sort(ventas)

array([20, 23, 28, 34, 45])

In [18]:
# varianza poblacional
np.var(ventas)

78.8

In [19]:
# desviacion est poblacional
np.std(ventas)

8.87693640846886

In [20]:
# varianza muestral
np.var(ventas, ddof=1)

98.5

In [21]:
# desviacion est muestral
np.std(ventas, ddof= 1)

9.924716620639604

In [23]:
# vector
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(1,100,15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [27]:
## aleatorios uniformes
# fijar semilla
np.random.seed(12)
## generan los numeros aleatorios
np.random.randint(0,25,10)

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])